[colors]
  [colors.primary]
    background = '#000000'
    foreground = '#eeedee'
  
  [colors.cursor]
    text = '#000000'
    cursor = '#7f7f7f'
  
  [colors.selection]
    text = '#000000'
    background = '#b4d5ff'
  
  [colors.normal]
    black   = '#4f4f4f'  # color0
    red     = '#fa6c5f'  # color1
    green   = '#a8fe60'  # color2
    yellow  = '#fffeb6'  # color3
    blue    = '#96cafd'  # color4
    magenta = '#fa72fc'  # color5
    cyan    = '#c6c4fd'  # color6
    white   = '#eeedee'  # color7
  
  [colors.bright]
    black   = '#7b7b7b'  # color8
    red     = '#fcb6af'  # color9
    green   = '#ceffab'  # color10
    yellow  = '#fffecc'  # color11
    blue    = '#b5dcfe'  # color12
    magenta = '#fb9bfe'  # color13
    cyan    = '#dfdffd'  # color14
    white   = '#fefffe'  # color15


[font]
size = 11.0

[font.normal]
family = "Fira Code"
style = "SemiBold"

[window]
decorations = "full"

[window.padding]
x = 15 
y = 15

[[keyboard.bindings]]
key = "Escape"
action = "Quit"


